[ProjectConfig]
project_name = "Editor Pong!"
project_author = "Alve Larsson, Daniel Thompson-Yvetot"
project_version = 0.01
project_graphics_api = "Vulkan"

[EditorConfig]
editor_default_scene = "None"

[EngineConfig]
engine_version = 0.14
